apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  # number of pods to run for tickets service
  replicas: 1
  # tell depl how to find created pods
  selector:
    matchLabels:
      app: tickets
  # template specifies how to create each individual pod
  template:
    metadata:
      labels:
        app: tickets
    # specify how the pod is going to behave
    spec:
      # containers inside pod (one for now)
      containers:
        # name is for logging purposes
        - name: tickets
          image: dasior/tickets
          # communicate environment variables from kubernetes into the container
          env:
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  # using ClusterIP by default
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
